### ISSUE TITLE
ipo scraper not working, warn message 'integer out of range' 

### ISSUE THREAD

**Issue by hardywu** [liangcai2012/savant-torrey-ranch#29]
execute `./bin/savantor   db   ipo -p` to scraper the ipo data.
The error message is as below:

``` sh
2015-06-03 16:21:40,378 INFO sqlalchemy.engine.base.Engine select version()
INFO:sqlalchemy.engine.base.Engine:select version()
2015-06-03 16:21:40,378 INFO sqlalchemy.engine.base.Engine {}
INFO:sqlalchemy.engine.base.Engine:{}
2015-06-03 16:21:40,379 INFO sqlalchemy.engine.base.Engine select current_schema()
INFO:sqlalchemy.engine.base.Engine:select current_schema()
2015-06-03 16:21:40,379 INFO sqlalchemy.engine.base.Engine {}
INFO:sqlalchemy.engine.base.Engine:{}
2015-06-03 16:21:40,380 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
INFO:sqlalchemy.engine.base.Engine:SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2015-06-03 16:21:40,380 INFO sqlalchemy.engine.base.Engine {}
INFO:sqlalchemy.engine.base.Engine:{}
2015-06-03 16:21:40,381 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
INFO:sqlalchemy.engine.base.Engine:SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2015-06-03 16:21:40,381 INFO sqlalchemy.engine.base.Engine {}
INFO:sqlalchemy.engine.base.Engine:{}
2015-06-03 16:21:40,382 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
INFO:sqlalchemy.engine.base.Engine:show standard_conforming_strings
2015-06-03 16:21:40,382 INFO sqlalchemy.engine.base.Engine {}
INFO:sqlalchemy.engine.base.Engine:{}
2015-06-03 16:21:40,383 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
INFO:sqlalchemy.engine.base.Engine:BEGIN (implicit)
2015-06-03 16:21:40,383 INFO sqlalchemy.engine.base.Engine SELECT exchange.id AS exchange_id, exchange.name AS exchange_name 
FROM exchange
INFO:sqlalchemy.engine.base.Engine:SELECT exchange.id AS exchange_id, exchange.name AS exchange_name 
FROM exchange
2015-06-03 16:21:40,383 INFO sqlalchemy.engine.base.Engine {}
INFO:sqlalchemy.engine.base.Engine:{}
2015-06-03 16:21:40,384 INFO sqlalchemy.engine.base.Engine SELECT industry.id AS industry_id, industry.name AS industry_name 
FROM industry
INFO:sqlalchemy.engine.base.Engine:SELECT industry.id AS industry_id, industry.name AS industry_name 
FROM industry
2015-06-03 16:21:40,385 INFO sqlalchemy.engine.base.Engine {}
INFO:sqlalchemy.engine.base.Engine:{}
2015-06-03 16:21:40,386 INFO sqlalchemy.engine.base.Engine SELECT sector.id AS sector_id, sector.name AS sector_name 
FROM sector
INFO:sqlalchemy.engine.base.Engine:SELECT sector.id AS sector_id, sector.name AS sector_name 
FROM sector
2015-06-03 16:21:40,386 INFO sqlalchemy.engine.base.Engine {}
INFO:sqlalchemy.engine.base.Engine:{}
2015-06-03 16:21:40,388 INFO sqlalchemy.engine.base.Engine SELECT company.id AS company_id, company.name AS company_name, company.symbol AS company_symbol, company.exchange_id AS company_exchange_id, company.sector_id AS company_sector_id, company.industry_id AS company_industry_id, company.market_cap AS company_market_cap, company.float_shares AS company_float_shares, company.prev_close AS company_prev_close, company.prev_volume AS company_prev_volume, company.trailing_pe AS company_trailing_pe, company.nasdaq_beta AS company_nasdaq_beta, company.date_updated AS company_date_updated 
FROM company 
WHERE company.symbol = %(symbol_1)s 
 LIMIT %(param_1)s
INFO:sqlalchemy.engine.base.Engine:SELECT company.id AS company_id, company.name AS company_name, company.symbol AS company_symbol, company.exchange_id AS company_exchange_id, company.sector_id AS company_sector_id, company.industry_id AS company_industry_id, company.market_cap AS company_market_cap, company.float_shares AS company_float_shares, company.prev_close AS company_prev_close, company.prev_volume AS company_prev_volume, company.trailing_pe AS company_trailing_pe, company.nasdaq_beta AS company_nasdaq_beta, company.date_updated AS company_date_updated 
FROM company 
WHERE company.symbol = %(symbol_1)s 
 LIMIT %(param_1)s
2015-06-03 16:21:40,388 INFO sqlalchemy.engine.base.Engine {'symbol_1': 'AAIT', 'param_1': 1}
INFO:sqlalchemy.engine.base.Engine:{'symbol_1': 'AAIT', 'param_1': 1}
2015-06-03 16:21:41,224 INFO sqlalchemy.engine.base.Engine SELECT company.id AS company_id, company.name AS company_name, company.symbol AS company_symbol, company.exchange_id AS company_exchange_id, company.sector_id AS company_sector_id, company.industry_id AS company_industry_id, company.market_cap AS company_market_cap, company.float_shares AS company_float_shares, company.prev_close AS company_prev_close, company.prev_volume AS company_prev_volume, company.trailing_pe AS company_trailing_pe, company.nasdaq_beta AS company_nasdaq_beta, company.date_updated AS company_date_updated 
FROM company 
WHERE company.symbol = %(symbol_1)s 
 LIMIT %(param_1)s
INFO:sqlalchemy.engine.base.Engine:SELECT company.id AS company_id, company.name AS company_name, company.symbol AS company_symbol, company.exchange_id AS company_exchange_id, company.sector_id AS company_sector_id, company.industry_id AS company_industry_id, company.market_cap AS company_market_cap, company.float_shares AS company_float_shares, company.prev_close AS company_prev_close, company.prev_volume AS company_prev_volume, company.trailing_pe AS company_trailing_pe, company.nasdaq_beta AS company_nasdaq_beta, company.date_updated AS company_date_updated 
FROM company 
WHERE company.symbol = %(symbol_1)s 
 LIMIT %(param_1)s
2015-06-03 16:21:41,224 INFO sqlalchemy.engine.base.Engine {'symbol_1': 'AAL', 'param_1': 1}
INFO:sqlalchemy.engine.base.Engine:{'symbol_1': 'AAL', 'param_1': 1}
2015-06-03 16:21:43,187 INFO sqlalchemy.engine.base.Engine SELECT company.id AS company_id, company.name AS company_name, company.symbol AS company_symbol, company.exchange_id AS company_exchange_id, company.sector_id AS company_sector_id, company.industry_id AS company_industry_id, company.market_cap AS company_market_cap, company.float_shares AS company_float_shares, company.prev_close AS company_prev_close, company.prev_volume AS company_prev_volume, company.trailing_pe AS company_trailing_pe, company.nasdaq_beta AS company_nasdaq_beta, company.date_updated AS company_date_updated 
FROM company 
WHERE company.name = %(name_1)s 
 LIMIT %(param_1)s
INFO:sqlalchemy.engine.base.Engine:SELECT company.id AS company_id, company.name AS company_name, company.symbol AS company_symbol, company.exchange_id AS company_exchange_id, company.sector_id AS company_sector_id, company.industry_id AS company_industry_id, company.market_cap AS company_market_cap, company.float_shares AS company_float_shares, company.prev_close AS company_prev_close, company.prev_volume AS company_prev_volume, company.trailing_pe AS company_trailing_pe, company.nasdaq_beta AS company_nasdaq_beta, company.date_updated AS company_date_updated 
FROM company 
WHERE company.name = %(name_1)s 
 LIMIT %(param_1)s
2015-06-03 16:21:43,187 INFO sqlalchemy.engine.base.Engine {'name_1': u'American Airlines Group, Inc.', 'param_1': 1}
INFO:sqlalchemy.engine.base.Engine:{'name_1': u'American Airlines Group, Inc.', 'param_1': 1}
2015-06-03 16:21:43,188 INFO sqlalchemy.engine.base.Engine SELECT exchange.id AS exchange_id, exchange.name AS exchange_name 
FROM exchange 
WHERE exchange.name = %(name_1)s 
 LIMIT %(param_1)s
INFO:sqlalchemy.engine.base.Engine:SELECT exchange.id AS exchange_id, exchange.name AS exchange_name 
FROM exchange 
WHERE exchange.name = %(name_1)s 
 LIMIT %(param_1)s
2015-06-03 16:21:43,188 INFO sqlalchemy.engine.base.Engine {'name_1': u'NASDAQ', 'param_1': 1}
INFO:sqlalchemy.engine.base.Engine:{'name_1': u'NASDAQ', 'param_1': 1}
2015-06-03 16:21:43,189 INFO sqlalchemy.engine.base.Engine SELECT industry.id AS industry_id, industry.name AS industry_name 
FROM industry 
WHERE industry.name = %(name_1)s 
 LIMIT %(param_1)s
INFO:sqlalchemy.engine.base.Engine:SELECT industry.id AS industry_id, industry.name AS industry_name 
FROM industry 
WHERE industry.name = %(name_1)s 
 LIMIT %(param_1)s
2015-06-03 16:21:43,189 INFO sqlalchemy.engine.base.Engine {'name_1': u'Major Airlines', 'param_1': 1}
INFO:sqlalchemy.engine.base.Engine:{'name_1': u'Major Airlines', 'param_1': 1}
2015-06-03 16:21:43,190 INFO sqlalchemy.engine.base.Engine SELECT sector.id AS sector_id, sector.name AS sector_name 
FROM sector 
WHERE sector.name = %(name_1)s 
 LIMIT %(param_1)s
INFO:sqlalchemy.engine.base.Engine:SELECT sector.id AS sector_id, sector.name AS sector_name 
FROM sector 
WHERE sector.name = %(name_1)s 
 LIMIT %(param_1)s
2015-06-03 16:21:43,190 INFO sqlalchemy.engine.base.Engine {'name_1': u'Services', 'param_1': 1}
INFO:sqlalchemy.engine.base.Engine:{'name_1': u'Services', 'param_1': 1}
2015-06-03 16:21:43,192 INFO sqlalchemy.engine.base.Engine INSERT INTO company (name, symbol, exchange_id, sector_id, industry_id, market_cap, float_shares, prev_close, prev_volume, trailing_pe, nasdaq_beta, date_updated) VALUES (%(name)s, %(symbol)s, %(exchange_id)s, %(sector_id)s, %(industry_id)s, %(market_cap)s, %(float_shares)s, %(prev_close)s, %(prev_volume)s, %(trailing_pe)s, %(nasdaq_beta)s, %(date_updated)s) RETURNING company.id
INFO:sqlalchemy.engine.base.Engine:INSERT INTO company (name, symbol, exchange_id, sector_id, industry_id, market_cap, float_shares, prev_close, prev_volume, trailing_pe, nasdaq_beta, date_updated) VALUES (%(name)s, %(symbol)s, %(exchange_id)s, %(sector_id)s, %(industry_id)s, %(market_cap)s, %(float_shares)s, %(prev_close)s, %(prev_volume)s, %(trailing_pe)s, %(nasdaq_beta)s, %(date_updated)s) RETURNING company.id
2015-06-03 16:21:43,192 INFO sqlalchemy.engine.base.Engine {'nasdaq_beta': None, 'market_cap': 29880414444, 'name': u'American Airlines Group, Inc.', 'sector_id': 1, 'date_updated': datetime.date(2015, 6, 3), 'industry_id': 1, 'symbol': 'AAL', 'prev_close': 43.775, 'exchange_id': 1, 'prev_volume': 12907685, 'float_shares': 687150000, 'trailing_pe': None}
INFO:sqlalchemy.engine.base.Engine:{'nasdaq_beta': None, 'market_cap': 29880414444, 'name': u'American Airlines Group, Inc.', 'sector_id': 1, 'date_updated': datetime.date(2015, 6, 3), 'industry_id': 1, 'symbol': 'AAL', 'prev_close': 43.775, 'exchange_id': 1, 'prev_volume': 12907685, 'float_shares': 687150000, 'trailing_pe': None}
2015-06-03 16:21:43,193 INFO sqlalchemy.engine.base.Engine ROLLBACK
INFO:sqlalchemy.engine.base.Engine:ROLLBACK
Traceback (most recent call last):
  File "./bin/savantor", line 43, in <module>
    args.func(args)
  File "./bin/savantor", line 36, in download_ipo
    from savant.scraper import populate_db
  File "/Users/hardy/Workshop/savant/bin/savant/scraper/populate_db.py", line 80, in <module>
    session.commit()
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2122, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2086, in _flush
    flush_context.execute()
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 761, in _emit_insert_statements
    execute(statement, params)
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1339, in _handle_dbapi_exception
    exc_info
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/Users/hardy/.pyenv/versions/anaconda-2.1.0/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.DataError) integer out of range
 [SQL: 'INSERT INTO company (name, symbol, exchange_id, sector_id, industry_id, market_cap, float_shares, prev_close, prev_volume, trailing_pe, nasdaq_beta, date_updated) VALUES (%(name)s, %(symbol)s, %(exchange_id)s, %(sector_id)s, %(industry_id)s, %(market_cap)s, %(float_shares)s, %(prev_close)s, %(prev_volume)s, %(trailing_pe)s, %(nasdaq_beta)s, %(date_updated)s) RETURNING company.id'] [parameters: {'nasdaq_beta': None, 'market_cap': 29880414444, 'name': u'American Airlines Group, Inc.', 'sector_id': 1, 'date_updated': datetime.date(2015, 6, 3), 'industry_id': 1, 'symbol': 'AAL', 'prev_close': 43.775, 'exchange_id': 1, 'prev_volume': 12907685, 'float_shares': 687150000, 'trailing_pe': None}]
```

**Comment by hardywu** [comment]
```
FROM company 
WHERE company.symbol = ?
 LIMIT ? OFFSET ?
2015-06-06 19:11:55,671 INFO sqlalchemy.engine.base.Engine ('AAL', 1, 0)
INFO:sqlalchemy.engine.base.Engine:('AAL', 1, 0)
Traceback (most recent call last):
  File "./bin/savantor", line 43, in <module>
    args.func(args)
  File "./bin/savantor", line 36, in download_ipo
    from savant.scraper import populate_company
  File "/Users/hardy/Workshop/savant/bin/savant/scraper/populate_company.py", line 30, in <module>
    data = scraper.scrape_nasdaq(symbol)
  File "/Users/hardy/Workshop/savant/bin/savant/scraper/__init__.py", line 156, in scrape_nasdaq
    key = tds[0].a.strings.next().strip()
StopIteration
```

**Comment by loki900718** [comment]
I didn't encounter this problem at all. Can you recheck it on your computer? Modify the main function in scraper.**init** to parse the page for "AAL".

**Comment by hardywu** [comment]
same issue.
